# Generated by Django 4.1 on 2022-10-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_rename_adress_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Addres',
        ),
    ]
